---
# EXAMPLE CONFIGS - MORE IN ansible/group_vars/all.yml

######################
# Service VIP address
######################
ansitheus_vip_address: "10.10.10.1"
# ansitheus_network_interface: "eth0"
keepalived_virtual_router_id: "82"

# The group which own node_config_directory, you can use a non-root
config_owner_user: "root"
config_owner_group: "root"
# network_interface: "eth0"

#####################
# Keepalived Password
#####################
keepalived_password: "secret"

################
# Docker options
################

docker_registry: ""
docker_namespace: ""
docker_registry_username: ""
docker_registry_password: ""

##################
# Service options
##################

enable_prometheus: "yes"
enable_node_exporter: "yes"
enable_cadvisor: "yes"
enable_grafana: "no"
enable_alertmanager: "yes"
enable_haproxy: "yes"
enable_mysqld_exporter: "no"
enable_fluentd: "no"
enable_openstack_exporter: "no"
enable_nginx_exporter: "no"

##################
# Port mappings
#################

prometheus_port: "9090"
alertmanager_port: "9093"
alertmanager_cluster_port: "9094"
node_exporter_port: "9100"
cadvisor_port: "8080"
grafana_port: "3000"
mysqld_exporter_port: "9104"
nginx_exporter_port: "9113"

###############
# Image version
###############

prometheus_version: "3.1.0"
alertmanager_version: "0.28.0"
node_exporter_version: "1.8.2"
cadvisor_version: "0.49.2"
grafana_version: "11.4.0"
haproxy_version: "lts-alpine"
mysqld_exporter_version: "0.15.1"
fluentd_version: "1.17"
nginx_exporter_version: "1.4.1"